TarkovTracker/TarkovTracker

- src/components/CollectTable.vue
- src/views/QuestInfo.vue
Fix a couple minor issues regarding displaying team need icons.
Moves team need icons in needed items page to next to the count.
Fixes team need displays on quest info pages
> Clean up team need displays

- firebase.json
- package-lock.json
- package.json
This loads a browsersync proxy 15 seconds after starting the firebase emulator, redirecting requests to port 5000 to port 4999 on localhost (set as firebase hosting emulator port). Any changes to dist directory from the watch build will trigger a browser refresh automatically.
> Add browsersync for hot reloading with firebase emulator

- functions/api.js
Adding an endpoint that allows you to see some basics about a token, including its permissions, created at, and general use
> Add API endpoint to verify token permissions

- functions/api.js
- functions/package-lock.json
- functions/package.json
- src/views/Settings.vue
Adding endpoints to update quests, hideout modules, quest and hideout objectives, and player level
`POST /api/v1/progress/level/:levelNumber` with no body required
`POST /api/v1/progress/quest/:questId` with a JSON object that contains `complete`
`POST /api/v1/progress/hideout/:hideoutId` with a JSON object that contains `complete`
`POST /api/v1/progress/quest/objective/:objectiveId` with a JSON object that contains `complete` and/or `have`
`POST /api/v1/progress/hideout/objective/:objectiveId` with a JSON object that contains `complete` and/or `have`
Resolves #9
> Add write endpoints to API

- src/main.js
- src/trackerCommonState.js
Was adding `g` to the start of hash to indicate git was the SCM - removed that to fix links to GitHub
> ignore semver scm flag

- src/components/QuestRow.vue
- src/store/modules/progress.js
- src/trackerGlobalMixin.js
- src/views/AllQuests.vue
This makes the UI do more in terms of preventing users from completing optional quests which they didn't actually complete due to failed prerequisites (ie Chemical Part 4/Out of Curiosity/Big Customer)
TODO: Explain to the user when completing an quest with alternatives, that the others will be marked as failed, like in the game.
> Hide quests blocked by failed prequisites

- src/components/QuestRow.vue
- src/trackerGlobalMixin.js
Just making it simple and blocking the ability to skip to them entirely until they select one of the previous optionals.
If BSG ever adds longer chains after the optionals, this logic will need to be made smarter, but works for the current alternative cases.
> Just force users to select which path first for alternatives

- functions/api.js
- functions/index.js
I discovered that Firebase Hosting route functions can only be run in us-central1. That's not ideal because my Firestore is in us-east4. So moving regions for the functions isn't helpful right now. The solution will need to be finding some low usage period, setting the site into a maintenance mode for a couple hours, and migrating the Auth users and Firestore to a new project, then switching the DNS over to that. Less ideal, but not an urgently needed change.
> Default regions for functions (project migration necessary)

- src/components/QuestRow.vue
- src/layouts/default/widgets/Search.vue
- src/trackerGlobalMixin.js
- src/views/QuestInfo.vue
1) Added Buttons to navigate quests to Quest detail (same functionality as in the quest list view. Also added tooltips to both places to better describe what the buttons do).
2) Sligthly changed behaviour of the Search bar at the top. Clicking a quest from the available list directly redirects you to it, you don't have to click Enter or the Search icon anymore.
> Quest detail enhancement - Quest navigation buttons (Resolves #111)

- functions/index.js
Will require people to re-create their teams unless I did a bunch of edits to teams. I could do that in the future if people had a problem recreating, but would prefer just to do the easy thing.
> Increase the maximum team size default to 10

- src/trackerCommonState.js
Hey!
I am using the website (and liking it a lot) and found an issue with some quests not showing up on the site even though I can see them in-game.
This occurs when a quest has no level requirement set (in quests.json, like in the case of "quest.id=196") and the "Hide Quests Above Level" filter is turned on.
The problematic filter seems to be this:
`(member.store.copy('progress/level') || 71) >= quest.require.level`
`(number >= undefined) => false`
I made this fix. Hope you like it.
(ps.: Formatting might be off, I don't know this repo's style yet.)
(edit1: Verified in local environment.)
> Set quest levelAvailability true if the quest has no level requirement set

- package-lock.json
- package.json
- src/views/Settings.vue
Allows external tools like The Hideout app to utilize TarkovTracker API tokens more easily
> Add QR code dialog for API tokens

- src/layouts/default/widgets/PlayerLevel.vue
Fixes #199.
Assumptions: 
Counter should wrap to the max value if decremented while at the min value.
Counter should wrap to the min value if incremented while at the max value.
New users should still start at 71.
This also fixes the issue for users who are in a broken state already.
There are a lot of ways to implement this so no worries if you would rather implement it some other way.
> Fix level tracker index going out of bounds

- src/trackerGlobalMixin.js
Fixes quest lookups not working when quest id doesn't match it's array index in quest.json.
Spotted due to the current broken state of the collector quest page.
https://tarkovtracker.io/quest/195/
> Fix quest lookups

- src/views/AllQuests.vue
Added a timer which shows the current time in tarkov next
to the map. The idea is that knowing the current time will
help to plan the raid for the map.
Don't show the time for Factory, as the time there is static.
> Show time in tarkov next to the map

- tarkov-tracker/src/components/neededitems/NeededItemCard.vue
Changes:
- Full height for item cards and their images
Before:
After:
> fix(item-card): unfilled image height

- tarkov-tracker/src/components/MapMarker.vue
- tarkov-tracker/src/components/tasks/TaskCard.vue
- tarkov-tracker/src/components/tasks/TaskLink.vue
Navigating between the map, the task cards, and the wiki feels a bit cumbersome and unintuitive.  
I can't tell you how many times I've clicked on the name of a task on the map expecting to be brought to that task, but instead, I'm redirected to the home page. I then have to go back to the tasks view and find the task in the list before can jump to the wiki to get the info I need.
This PR makes two changes for more convenient navigation:
1. `TaskLink`s now scroll the page to their corresponding `TaskCard` if one is present on the page. 
2. `MapMarker`s now include a link to the wiki in their tooltip
Before:
After:
> [Feature] Add wiki link to map card and scroll to task when task name is clicked

- functions/api/v2/index.js
- tarkov-tracker/src/components/tasks/TaskCard.vue
(this pr resolved #389 )
This pull request addresses the issue where a user completes a task via the API without meeting the minimum level requirement for that task. The solution ensures that if a player's current level is below the completed task's minimum level, the system will automatically update the player's level to match this minimum requirement.
- If the player's level is below the task's minimum, their level is updated to the task's minimum level requirement.
- The Frontend tarkovtracker.io
- The functions tarkovtracker.io/api/v2/progress/task/{taskid}
Please review the changes and provide any feedback or suggestions for improvement.
Thank you!
> resolves #389 | Automatic level adjustment on Task Completion via API and WEB

- tarkov-tracker/src/components/tasks/TaskObjective.vue
The Establish Contact task has an objective of type traderStanding which would otherwise display as mdi-help-circle
> Fix missing icon for traderStanding objective

- tarkov-tracker/src/pages/TaskList.vue
If the hideGlobalTasks parameter is active, the tasks-per-map counter needs to ignore global tasks. We needs to use the same logic that the task list uses to filter out global tasks. The task list checks the map property of the task object for null.
Resolves #424
> Take "hideGlobalTasks" parameter into account
