package-lock.json
public/index.html
src/components/FirebaseAuth.vue
src/fireapp.js
src/main.js
src/plugins/vuetify.js

Update how the firebase SDK is imported to make sure it was happy
Resolves #13

Update firebase SDK to make it happy

---

src/components/SharedFooter.vue
src/main.js

Changed tarkovdata commit finding to be 100% accurate. Now pulls the data commit directly from the current tracker's commit tree from the GitHub API.
Displays the amount of time since each commit to let users know how fresh the data and changes are to hopefully encourage community involvement.

Improve tracker version display

---

src/main.js

Missed a call in #23 to make sure the new version display worked in all situations

BUG: Fix missing GitHub api call

---

firebase.json
firestore.rules
functions/index.js
src/store/modules/firesys.js
src/views/Settings.vue

Creating an API so users can allow other tools to utilize their Tarkov Tracker progression data to provide them tailored information

WIP: Create Tarkov Tracker API

---

README.md
firebase.json
functions/api.js
functions/index.js
package.json
src/views/Settings.vue

Refactored the functions out slightly as well, and started using an express app to make API endpoints super simple

Add team progress API endpoint

---

functions/api.js

Uses the hide teammates flag set by the web client to add a flag to the progress API calls

Add hidden teammates flag to API progress calls

---

src/components/QuestRow.vue
src/components/TarkovItem.vue
src/layouts/default/Drawer.vue
src/main.js
src/plugins/vuetify.js
src/router/index.js
src/store/modules/progress.js
src/store/modules/user.js
src/trackerCommonState.js
src/trackerGlobalMixin.js
src/views/AllQuests.vue

Concepted all quests view

---

src/views/HideoutTable.vue

AKA stop the christmas tree from showing up when its not enabled

Don't show stations that are disabled

---

package.json

Add npm script to pull latest submodule commit

---

src/views/Contributors.vue

Change development contributors to repo commits

---

src/components/LoyaltyStatCard.vue
src/views/Dashboard.vue

Adding a new type of card specifically for loyalty stats to show off @Hanzik's trader rep work - this also has a couple commits to tarkovdata to fix reputation values so it should show accurately now.

Loyalty stat cards

---

public/index.html

Collect some more performance/metrics from CloudFlare

Add cloudflare analytics tag

---

functions/api.js
functions/index.js

Should reduce latency to/from firestore and thus runtime of the functions (they default to us-central)

Set default function region to us-east4 to be near firestore

---

src/components/HideoutModule.vue
src/components/LoyaltyStatCard.vue
src/components/TraderTag.vue
src/layouts/default/widgets/Search.vue
src/trackerGlobalMixin.js
src/views/AllQuests.vue
src/views/Dashboard.vue
src/views/QuestInfo.vue

Using the new schema from tarkovdata

Switch to trader ids instead of names

---

src/trackerCommonState.js
src/views/AllQuests.vue

Fixes the map count badges that I broke with the map ID changes

Fix map count indexing

---

src/components/CollectTable.vue
src/components/SkillCard.vue
src/views/Settings.vue

Making a pass on some colors that I felt like should be tweaked, and a couple wording changes

Color & minor wording/cosmetic changes

---

src/App.vue
src/components/FirebaseAuth.vue
src/fireapp.js
src/main.js

Adds a maintenance mode flag which is pulled from Firebase RemoteConfig, and when set to true, will send new visitors to a maintenance mode page.

Add maintenance mode remote config setup

---

.github/workflows/publish-release-deploy-production.yml
src/firebaseConfig.js
src/layouts/default/widgets/DrawerHeader.vue

Migrating to a new project to facilitate moving Firestore regions

Change firebase references to new project

---

src/firebaseConfig.js

Adds the firebase config object for the testing environment

Add testing environment config

---

src/views/Dashboard.vue

Adding numerical progress on main dashboard (Issue: https://github.com/TarkovTracker/TarkovTracker/issues/177)

Adding numerical progress on dashboard

---

src/views/NeededItems.vue

not much here, was just trying to get familiar with the codebase and noticed this

Update NeededItems.vue to fix typo

---

src/components/QuestObjective.vue

Similar to 'mark' or 'place' we should also show a hint (if there is one) for 'locate' objectives

Show hint for quest (if there is one)

---

tarkov-tracker/src/pages/TrackerDashboard.vue

Hi @thaddeus, I'd like to propose this little fix addressing the calculation of completed tasks on the dashboard and replacing the hardcoded value of completed objectives.
Here's the list of changes:
- fix completed tasks counter
- add missing completed objectives counter
- inserted final newline (as per editorconfig)
Context:
- This is my first time working with Vue. Usually, I'm the React team kid. I want to play more with Vue, so if things aren't how they're supposed to be in this PR - please lmk.
- There is a prettier config and editor config, but when I formatted the file got a lot of changes. It looks like the format wasn't being used for this page, so I intentionally did not use it either. If it's okay to re-format the page with the prettier configuration in the repo - please lmk …

fix(dashboard): missing stats

---

tarkov-tracker/src/components/MapMarker.vue
tarkov-tracker/src/pages/TaskList.vue

When questing with friends, the map with it's markers is very useful to see what objectives everyone has on the map. However, it can be quite hard to keep track which quests I have active, and which quests my friends have; especially when we have 20 shoreline quests.
As of right now, I have to alt-tab out of the game, to the TarkovTracker website, and select "YOURSELF" to see which quests I have active, then switch to "ALL" and have to match which quests we have in common. This can become quite frustrating. It would be awesome to see a difference between which quests I have, and which quests my teammates have (but I dont), so I can easily see what my objective are, while also being able to see which objectives my buddies have
This PR adds the property `users` to the `visibleGPS` object …

[FEATURE] Map marker colors 

---

tarkov-tracker/src/components/hideout/HideoutCard.vue

Fix template typo in Hideout page

---

tarkov-tracker/src/locales/es.json5

Fixed error in the Spanish translation of the required keys.

Fixed error in the Spanish translation of the required keys.

---

tarkov-tracker/src/composables/tarkovdata.js
tarkov-tracker/src/utils/tarkovdataquery.js

The user's language is obtained from i18n and sent to GraphQL for the request.

Missions are obtained in the language selected by the user.
